<?php
echo "<!DOCTYPE html>\n";
echo "<html style=\"--accent-color: #2e94b9\" lang=\"zh-CN\">\n";
echo "  <head>\n";
echo "    <meta charset=\"UTF-8\" />\n";
echo "    <meta\n";
echo "      name=\"viewport\"\n";
echo "      content=\"width=device-width, initial-scale=1, user-scalable=no\"\n";
echo "    />\n";
echo "    <title>亿方教材助手网页版</title>\n";
echo "    <style id=\"classic-theme-styles-inline-css\" type=\"text/css\">\n";
echo "      .wp-block-button__link {\n";
echo "        color: #fff;\n";
echo "        background-color: #32373c;\n";
echo "        border-radius: 9999px;\n";
echo "        box-shadow: none;\n";
echo "        text-decoration: none;\n";
echo "        padding: calc(0.667em + 2px) calc(1.333em + 2px);\n";
echo "        font-size: 1.125em;\n";
echo "      }\n";
echo "      .wp-block-file__button {\n";
echo "        background: #32373c;\n";
echo "        color: #fff;\n";
echo "        text-decoration: none;\n";
echo "      }\n";
echo "    </style>\n";
echo "    <link\n";
echo "      rel=\"stylesheet\"\n";
echo "      id=\"fancybox-css\"\n";
echo "      href=\"css/jquery.fancybox.min.css?ver=6.6.1\"\n";
echo "      type=\"text/css\"\n";
echo "      media=\"all\"\n";
echo "    />\n";
echo "    <link\n";
echo "      rel=\"stylesheet\"\n";
echo "      id=\"remixicon-css\"\n";
echo "      href=\"css/remixicon.min.css?ver=6.6.1\"\n";
echo "      type=\"text/css\"\n";
echo "      media=\"all\"\n";
echo "    />\n";
echo "    <link\n";
echo "      rel=\"stylesheet\"\n";
echo "      id=\"autumn-style-css\"\n";
echo "      href=\"css/style-5.6.1.css?ver=5.6.1\"\n";
echo "      type=\"text/css\"\n";
echo "      media=\"all\"\n";
echo "    />\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/jquery.min.js?ver=3.7.1\"\n";
echo "      id=\"jquery-core-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/jquery-migrate.min.js?ver=3.4.1\"\n";
echo "      id=\"jquery-migrate-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/jquery.fancybox.min.js?ver=6.6.1\"\n";
echo "      id=\"fancybox-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/lazysizes.min.js?ver=6.6.1\"\n";
echo "      id=\"lazysizes-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/ls.unveilhooks.min.js?ver=6.6.1\"\n";
echo "      id=\"unveilhooks-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/theia-sticky-sidebar.js?ver=1.7\"\n";
echo "      id=\"sticky-sidebar-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/script-5.6.1.js?ver=5.6.1\"\n";
echo "      id=\"autumn-script-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/qrcode.min.js?ver=6.6.1\"\n";
echo "      id=\"qrcodejs-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/html2canvas.min.js?ver=6.6.1\"\n";
echo "      id=\"html2canvas-js\"\n";
echo "    ></script>\n";
echo "    <style type=\"text/css\"></style>\n";
echo "    <style id=\"theia-sticky-sidebar-stylesheet-TSS\">\n";
echo "      .theiaStickySidebar:after {\n";
echo "        content: \"\";\n";
echo "        display: table;\n";
echo "        clear: both;\n";
echo "      }\n";
echo "    </style>\n";
echo "  </head>\n";
echo "  <body\n";
echo "    id=\"body\"\n";
echo "    class=\"page-template page-template-pages page-template-page-full page-template-pagespage-full-php page page-id-5865 navbar-sticky\"\n";
echo "  >\n";
echo "    <script type=\"text/javascript\">\n";
echo "      init_color_scheme(true);\n";
echo "    </script>\n";
echo "    <div class=\"site\" style=\"height: auto !important\">\n";
echo "      <div class=\"site-content container\" style=\"height: auto !important\">\n";
echo "        <div class=\"row\" style=\"height: auto !important\">\n";
echo "          <div\n";
echo "            class=\"col-lg-12\"\n";
echo "            style=\"height: auto !important; min-height: 0px !important\"\n";
echo "          >\n";
echo "            <div class=\"content-area\" style=\"height: auto !important\">\n";
echo "              <main class=\"site-main\" style=\"height: auto !important\">\n";
echo "                <article class=\"type-post post\" style=\"height: auto !important\">\n";
echo "                  <header class=\"entry-header page\">\n";
echo "                    <h1 align=\"center\">\n";
echo "                        亿方教材助手网页版\n";
echo "                    </h1>\n";
echo "                  </header>\n";
echo "                  <div class=\"entry-wrapper\" style=\"height: auto !important\">\n";
echo "                    <div\n";
echo "                      class=\"entry-content u-clearfix\"\n";
echo "                      style=\"height: auto !important\"\n";
echo "                    >\n";
echo "                      <style>\n";
echo "                        #conversionForm .custom-input-container {\n";
echo "                          display: flex;\n";
echo "                          flex-direction: column;\n";
echo "                        }\n";
echo "                        #conversionForm .custom-input {\n";
echo "                          width: 100%;\n";
echo "                          padding: 12px;\n";
echo "                          font-size: 16px;\n";
echo "                          border: 2px solid #ccc;\n";
echo "                          border-radius: 4px;\n";
echo "                          box-sizing: border-box;\n";
echo "                          margin-bottom: 10px;\n";
echo "                          height: 60px;\n";
echo "                        }\n";
echo "                        #conversionForm .custom-button-row {\n";
echo "                          display: flex;\n";
echo "                          justify-content: flex-start;\n";
echo "                          align-items: center;\n";
echo "                        }\n";
echo "                        #conversionForm .custom-button {\n";
echo "                          background-color: #4caf50;\n";
echo "                          color: white;\n";
echo "                          padding: 5px 7px;\n";
echo "                          border: none;\n";
echo "                          border-radius: 4px;\n";
echo "                          cursor: pointer;\n";
echo "                          font-size: 16px;\n";
echo "                          height: 40px;\n";
echo "                        }\n";
echo "                        #conversionForm .clear-button {\n";
echo "                          background-color: #1e99bb;\n";
echo "                          white-space: nowrap;\n";
echo "                          margin-left: 10px;\n";
echo "                        }\n";
echo "                        #conversionForm .clear-button-2 {\n";
echo "                          margin-left: 10px;\n";
echo "                        }\n";
echo "                        #conversionForm .custom-button:hover,\n";
echo "                        #conversionForm .clear-button:hover {\n";
echo "                          background-color: #45a049;\n";
echo "                        }\n";
echo "                      </style>\n";
echo "                      <p><meta name=\"referrer\" content=\"never\" /></p>\n";
echo "                      <form id=\"conversionForm\">\n";
echo "                        <div class=\"custom-input-container\">\n";
echo "                          <div>\n";
echo "                            <input\n";
echo "                              type=\"text\"\n";
echo "                              id=\"contentInput\"\n";
echo "                              class=\"custom-input\"\n";
echo "                              placeholder=\"请输入要下载的教材网址\"\n";
echo "                              required=\"\"\n";
echo "                            />\n";
echo "                          </div>\n";
echo "                          <div class=\"custom-button-row\">\n";
echo "                            <button\n";
echo "                              type=\"submit\"\n";
echo "                              id=\"convertButton\"\n";
echo "                              class=\"custom-button\"\n";
echo "                            >\n";
echo "                              打开下载链接</button\n";
echo "                            ><br />\n";
echo "                            <button\n";
echo "                              type=\"button\"\n";
echo "                              id=\"copyButton\"\n";
echo "                              class=\"custom-button clear-button-2\"\n";
echo "                            >\n";
echo "                              复制下载链接</button\n";
echo "                            ><br />\n";
echo "                            <button\n";
echo "                              type=\"button\"\n";
echo "                              id=\"clearButton\"\n";
echo "                              class=\"custom-button clear-button\"\n";
echo "                            >\n";
echo "                              清空输入框\n";
echo "                            </button>\n";
echo "                          </div>\n";
echo "                        </div>\n";
echo "                      </form>\n";
echo "                      <p>\n";
echo "                        <script>\n";
echo "                          document\n";
echo "                            .getElementById(\"conversionForm\")\n";
echo "                            .addEventListener(\"submit\", function (event) {\n";
echo "                              event.preventDefault();\n";
echo "                              var contentInput =\n";
echo "                                document.getElementById(\"contentInput\").value;\n";
echo "                              var id = extractIDFromURL(contentInput);\n";
echo "                              if (id) {\n";
echo "                                var downloadLink =\n";
echo "                                  \"https://r3-ndr.ykt.cbern.com.cn/edu_product/esp/assets_document/\" +\n";
echo "                                  id +\n";
echo "                                  \".pkg/pdf.pdf\";\n";
echo "                                openWindowWithNoReferer(downloadLink);\n";
echo "                              } else {\n";
echo "                                alert(\"输入内容无法匹配，请重新输入。\");\n";
echo "                              }\n";
echo "                            });\n";
echo "                          document\n";
echo "                            .getElementById(\"copyButton\")\n";
echo "                            .addEventListener(\"click\", function (event) {\n";
echo "                              var contentInput =\n";
echo "                                document.getElementById(\"contentInput\").value;\n";
echo "                              var id = extractIDFromURL(contentInput);\n";
echo "                              if (id) {\n";
echo "                                var downloadLink =\n";
echo "                                  \"https://r3-ndr.ykt.cbern.com.cn/edu_product/esp/assets_document/\" +\n";
echo "                                  id +\n";
echo "                                  \".pkg/pdf.pdf\";\n";
echo "                                copyToClipboard(downloadLink);\n";
echo "                                alert(\"链接已复制到剪贴板。\");\n";
echo "                              } else {\n";
echo "                                alert(\"输入内容无法匹配，请重新输入。\");\n";
echo "                              }\n";
echo "                            });\n";
echo "                          document\n";
echo "                            .getElementById(\"clearButton\")\n";
echo "                            .addEventListener(\"click\", function (event) {\n";
echo "                              document.getElementById(\"contentInput\").value =\n";
echo "                                \"\";\n";
echo "                            });\n";
echo "                          function extractIDFromURL(url) {\n";
echo "                            var regex = /contentId=([\\w-]+)/;\n";
echo "                            var match = url.match(regex);\n";
echo "                            if (match && match[1]) {\n";
echo "                              return match[1];\n";
echo "                            }\n";
echo "                            return \"\";\n";
echo "                          }\n";
echo "                          function openWindowWithNoReferer(url) {\n";
echo "                            var newWindow = window.open(\"\", \"_blank\");\n";
echo "                            newWindow.opener = null;\n";
echo "                            newWindow.location = url;\n";
echo "                            newWindow.addEventListener(\n";
echo "                              \"DOMContentLoaded\",\n";
echo "                              function () {\n";
echo "                                newWindow.document.referrer = null;\n";
echo "                              }\n";
echo "                            );\n";
echo "                          }\n";
echo "                          function copyToClipboard(text) {\n";
echo "                            var textarea = document.createElement(\"textarea\");\n";
echo "                            textarea.value = text;\n";
echo "                            textarea.style.position = \"fixed\"; // Ensure the textarea is positioned off the screen\n";
echo "                            document.body.appendChild(textarea);\n";
echo "                            textarea.select();\n";
echo "                            document.execCommand(\"copy\");\n";
echo "                            document.body.removeChild(textarea);\n";
echo "                          }\n";
echo "                        </script>\n";
echo "                      </p>\n";
echo "                      <div class=\"tag-share\"></div>\n";
echo "                      <p>\n";
echo "                        ✅亿方教材助手电脑软件：<a\n";
echo "                          href=\"https://gitlab.com/xiaoyangtech1/AnyTextbookDownloader\"\n";
echo "                          rel=\"noopener\"\n";
echo "                          target=\"_blank\"\n";
echo "                          >点击查看开源地址</a\n";
echo "                        >\n";
echo "                      </p>\n";
echo "                      <p>\n";
echo "                        由教育部主办的国家中小学智慧教育平台，提供了小学、初中和高中各版本各学科的PDF版教材，注册账号后可以网站浏览。\n";
echo "                      </p>\n";
echo "                      <p>\n";
echo "                        如果<mark>不注册账号</mark>，并且还要将电子版教材<mark>下载</mark>到本地<mark>查看</mark>、<mark>编辑</mark>、<mark>标注</mark>或<mark>打印</mark>，那么可以通过此页面的功能实现这个需求。\n";
echo "                      </p>\n";
echo "                  </div>\n";
echo "                </article>\n";
echo "              </main>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "      <footer class=\"site-footer\">\n";
echo "        <div class=\"site-info\">\n";
echo "          <p>Copyright 2024.<a rel=\"nofollow\" target=\"_blank\" href=\"https://kejiyuzhe.chgskj.cn/\">科技语者</a> All Rights Reserved.&nbsp;</p>\n";
echo "        </div>\n";
echo "      </footer>\n";
echo "    </div>\n";
echo "    <script type=\"text/javascript\"></script>\n";
echo "\n";
echo "    <div class=\"slide-bar\"></div>\n";
echo "\n";
echo "    <style id=\"global-styles-inline-css\" type=\"text/css\">\n";
echo "      :root {\n";
echo "        --wp--preset--aspect-ratio--square: 1;\n";
echo "        --wp--preset--aspect-ratio--4-3: 4/3;\n";
echo "        --wp--preset--aspect-ratio--3-4: 3/4;\n";
echo "        --wp--preset--aspect-ratio--3-2: 3/2;\n";
echo "        --wp--preset--aspect-ratio--2-3: 2/3;\n";
echo "        --wp--preset--aspect-ratio--16-9: 16/9;\n";
echo "        --wp--preset--aspect-ratio--9-16: 9/16;\n";
echo "        --wp--preset--color--black: #000000;\n";
echo "        --wp--preset--color--cyan-bluish-gray: #abb8c3;\n";
echo "        --wp--preset--color--white: #ffffff;\n";
echo "        --wp--preset--color--pale-pink: #f78da7;\n";
echo "        --wp--preset--color--vivid-red: #cf2e2e;\n";
echo "        --wp--preset--color--luminous-vivid-orange: #ff6900;\n";
echo "        --wp--preset--color--luminous-vivid-amber: #fcb900;\n";
echo "        --wp--preset--color--light-green-cyan: #7bdcb5;\n";
echo "        --wp--preset--color--vivid-green-cyan: #00d084;\n";
echo "        --wp--preset--color--pale-cyan-blue: #8ed1fc;\n";
echo "        --wp--preset--color--vivid-cyan-blue: #0693e3;\n";
echo "        --wp--preset--color--vivid-purple: #9b51e0;\n";
echo "        --wp--preset--gradient--vivid-cyan-blue-to-vivid-purple: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgba(6, 147, 227, 1) 0%,\n";
echo "          rgb(155, 81, 224) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--light-green-cyan-to-vivid-green-cyan: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(122, 220, 180) 0%,\n";
echo "          rgb(0, 208, 130) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgba(252, 185, 0, 1) 0%,\n";
echo "          rgba(255, 105, 0, 1) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--luminous-vivid-orange-to-vivid-red: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgba(255, 105, 0, 1) 0%,\n";
echo "          rgb(207, 46, 46) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--very-light-gray-to-cyan-bluish-gray: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(238, 238, 238) 0%,\n";
echo "          rgb(169, 184, 195) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--cool-to-warm-spectrum: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(74, 234, 220) 0%,\n";
echo "          rgb(151, 120, 209) 20%,\n";
echo "          rgb(207, 42, 186) 40%,\n";
echo "          rgb(238, 44, 130) 60%,\n";
echo "          rgb(251, 105, 98) 80%,\n";
echo "          rgb(254, 248, 76) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--blush-light-purple: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(255, 206, 236) 0%,\n";
echo "          rgb(152, 150, 240) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--blush-bordeaux: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(254, 205, 165) 0%,\n";
echo "          rgb(254, 45, 45) 50%,\n";
echo "          rgb(107, 0, 62) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--luminous-dusk: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(255, 203, 112) 0%,\n";
echo "          rgb(199, 81, 192) 50%,\n";
echo "          rgb(65, 88, 208) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--pale-ocean: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(255, 245, 203) 0%,\n";
echo "          rgb(182, 227, 212) 50%,\n";
echo "          rgb(51, 167, 181) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--electric-grass: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(202, 248, 128) 0%,\n";
echo "          rgb(113, 206, 126) 100%\n";
echo "        );\n";
echo "        --wp--preset--gradient--midnight: linear-gradient(\n";
echo "          135deg,\n";
echo "          rgb(2, 3, 129) 0%,\n";
echo "          rgb(40, 116, 252) 100%\n";
echo "        );\n";
echo "        --wp--preset--font-size--small: 13px;\n";
echo "        --wp--preset--font-size--medium: 20px;\n";
echo "        --wp--preset--font-size--large: 36px;\n";
echo "        --wp--preset--font-size--x-large: 42px;\n";
echo "        --wp--preset--spacing--20: 0.44rem;\n";
echo "        --wp--preset--spacing--30: 0.67rem;\n";
echo "        --wp--preset--spacing--40: 1rem;\n";
echo "        --wp--preset--spacing--50: 1.5rem;\n";
echo "        --wp--preset--spacing--60: 2.25rem;\n";
echo "        --wp--preset--spacing--70: 3.38rem;\n";
echo "        --wp--preset--spacing--80: 5.06rem;\n";
echo "        --wp--preset--shadow--natural: 6px 6px 9px rgba(0, 0, 0, 0.2);\n";
echo "        --wp--preset--shadow--deep: 12px 12px 50px rgba(0, 0, 0, 0.4);\n";
echo "        --wp--preset--shadow--sharp: 6px 6px 0px rgba(0, 0, 0, 0.2);\n";
echo "        --wp--preset--shadow--outlined: 6px 6px 0px -3px rgba(255, 255, 255, 1),\n";
echo "          6px 6px rgba(0, 0, 0, 1);\n";
echo "        --wp--preset--shadow--crisp: 6px 6px 0px rgba(0, 0, 0, 1);\n";
echo "      }\n";
echo "      :where(.is-layout-flex) {\n";
echo "        gap: 0.5em;\n";
echo "      }\n";
echo "      :where(.is-layout-grid) {\n";
echo "        gap: 0.5em;\n";
echo "      }\n";
echo "      body .is-layout-flex {\n";
echo "        display: flex;\n";
echo "      }\n";
echo "      .is-layout-flex {\n";
echo "        flex-wrap: wrap;\n";
echo "        align-items: center;\n";
echo "      }\n";
echo "      .is-layout-flex > :is(*, div) {\n";
echo "        margin: 0;\n";
echo "      }\n";
echo "      body .is-layout-grid {\n";
echo "        display: grid;\n";
echo "      }\n";
echo "      .is-layout-grid > :is(*, div) {\n";
echo "        margin: 0;\n";
echo "      }\n";
echo "      :where(.wp-block-columns.is-layout-flex) {\n";
echo "        gap: 2em;\n";
echo "      }\n";
echo "      :where(.wp-block-columns.is-layout-grid) {\n";
echo "        gap: 2em;\n";
echo "      }\n";
echo "      :where(.wp-block-post-template.is-layout-flex) {\n";
echo "        gap: 1.25em;\n";
echo "      }\n";
echo "      :where(.wp-block-post-template.is-layout-grid) {\n";
echo "        gap: 1.25em;\n";
echo "      }\n";
echo "      .has-black-color {\n";
echo "        color: var(--wp--preset--color--black) !important;\n";
echo "      }\n";
echo "      .has-cyan-bluish-gray-color {\n";
echo "        color: var(--wp--preset--color--cyan-bluish-gray) !important;\n";
echo "      }\n";
echo "      .has-white-color {\n";
echo "        color: var(--wp--preset--color--white) !important;\n";
echo "      }\n";
echo "      .has-pale-pink-color {\n";
echo "        color: var(--wp--preset--color--pale-pink) !important;\n";
echo "      }\n";
echo "      .has-vivid-red-color {\n";
echo "        color: var(--wp--preset--color--vivid-red) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-orange-color {\n";
echo "        color: var(--wp--preset--color--luminous-vivid-orange) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-amber-color {\n";
echo "        color: var(--wp--preset--color--luminous-vivid-amber) !important;\n";
echo "      }\n";
echo "      .has-light-green-cyan-color {\n";
echo "        color: var(--wp--preset--color--light-green-cyan) !important;\n";
echo "      }\n";
echo "      .has-vivid-green-cyan-color {\n";
echo "        color: var(--wp--preset--color--vivid-green-cyan) !important;\n";
echo "      }\n";
echo "      .has-pale-cyan-blue-color {\n";
echo "        color: var(--wp--preset--color--pale-cyan-blue) !important;\n";
echo "      }\n";
echo "      .has-vivid-cyan-blue-color {\n";
echo "        color: var(--wp--preset--color--vivid-cyan-blue) !important;\n";
echo "      }\n";
echo "      .has-vivid-purple-color {\n";
echo "        color: var(--wp--preset--color--vivid-purple) !important;\n";
echo "      }\n";
echo "      .has-black-background-color {\n";
echo "        background-color: var(--wp--preset--color--black) !important;\n";
echo "      }\n";
echo "      .has-cyan-bluish-gray-background-color {\n";
echo "        background-color: var(--wp--preset--color--cyan-bluish-gray) !important;\n";
echo "      }\n";
echo "      .has-white-background-color {\n";
echo "        background-color: var(--wp--preset--color--white) !important;\n";
echo "      }\n";
echo "      .has-pale-pink-background-color {\n";
echo "        background-color: var(--wp--preset--color--pale-pink) !important;\n";
echo "      }\n";
echo "      .has-vivid-red-background-color {\n";
echo "        background-color: var(--wp--preset--color--vivid-red) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-orange-background-color {\n";
echo "        background-color: var(\n";
echo "          --wp--preset--color--luminous-vivid-orange\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-amber-background-color {\n";
echo "        background-color: var(\n";
echo "          --wp--preset--color--luminous-vivid-amber\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-light-green-cyan-background-color {\n";
echo "        background-color: var(--wp--preset--color--light-green-cyan) !important;\n";
echo "      }\n";
echo "      .has-vivid-green-cyan-background-color {\n";
echo "        background-color: var(--wp--preset--color--vivid-green-cyan) !important;\n";
echo "      }\n";
echo "      .has-pale-cyan-blue-background-color {\n";
echo "        background-color: var(--wp--preset--color--pale-cyan-blue) !important;\n";
echo "      }\n";
echo "      .has-vivid-cyan-blue-background-color {\n";
echo "        background-color: var(--wp--preset--color--vivid-cyan-blue) !important;\n";
echo "      }\n";
echo "      .has-vivid-purple-background-color {\n";
echo "        background-color: var(--wp--preset--color--vivid-purple) !important;\n";
echo "      }\n";
echo "      .has-black-border-color {\n";
echo "        border-color: var(--wp--preset--color--black) !important;\n";
echo "      }\n";
echo "      .has-cyan-bluish-gray-border-color {\n";
echo "        border-color: var(--wp--preset--color--cyan-bluish-gray) !important;\n";
echo "      }\n";
echo "      .has-white-border-color {\n";
echo "        border-color: var(--wp--preset--color--white) !important;\n";
echo "      }\n";
echo "      .has-pale-pink-border-color {\n";
echo "        border-color: var(--wp--preset--color--pale-pink) !important;\n";
echo "      }\n";
echo "      .has-vivid-red-border-color {\n";
echo "        border-color: var(--wp--preset--color--vivid-red) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-orange-border-color {\n";
echo "        border-color: var(\n";
echo "          --wp--preset--color--luminous-vivid-orange\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-amber-border-color {\n";
echo "        border-color: var(--wp--preset--color--luminous-vivid-amber) !important;\n";
echo "      }\n";
echo "      .has-light-green-cyan-border-color {\n";
echo "        border-color: var(--wp--preset--color--light-green-cyan) !important;\n";
echo "      }\n";
echo "      .has-vivid-green-cyan-border-color {\n";
echo "        border-color: var(--wp--preset--color--vivid-green-cyan) !important;\n";
echo "      }\n";
echo "      .has-pale-cyan-blue-border-color {\n";
echo "        border-color: var(--wp--preset--color--pale-cyan-blue) !important;\n";
echo "      }\n";
echo "      .has-vivid-cyan-blue-border-color {\n";
echo "        border-color: var(--wp--preset--color--vivid-cyan-blue) !important;\n";
echo "      }\n";
echo "      .has-vivid-purple-border-color {\n";
echo "        border-color: var(--wp--preset--color--vivid-purple) !important;\n";
echo "      }\n";
echo "      .has-vivid-cyan-blue-to-vivid-purple-gradient-background {\n";
echo "        background: var(\n";
echo "          --wp--preset--gradient--vivid-cyan-blue-to-vivid-purple\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-light-green-cyan-to-vivid-green-cyan-gradient-background {\n";
echo "        background: var(\n";
echo "          --wp--preset--gradient--light-green-cyan-to-vivid-green-cyan\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-amber-to-luminous-vivid-orange-gradient-background {\n";
echo "        background: var(\n";
echo "          --wp--preset--gradient--luminous-vivid-amber-to-luminous-vivid-orange\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-luminous-vivid-orange-to-vivid-red-gradient-background {\n";
echo "        background: var(\n";
echo "          --wp--preset--gradient--luminous-vivid-orange-to-vivid-red\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-very-light-gray-to-cyan-bluish-gray-gradient-background {\n";
echo "        background: var(\n";
echo "          --wp--preset--gradient--very-light-gray-to-cyan-bluish-gray\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-cool-to-warm-spectrum-gradient-background {\n";
echo "        background: var(\n";
echo "          --wp--preset--gradient--cool-to-warm-spectrum\n";
echo "        ) !important;\n";
echo "      }\n";
echo "      .has-blush-light-purple-gradient-background {\n";
echo "        background: var(--wp--preset--gradient--blush-light-purple) !important;\n";
echo "      }\n";
echo "      .has-blush-bordeaux-gradient-background {\n";
echo "        background: var(--wp--preset--gradient--blush-bordeaux) !important;\n";
echo "      }\n";
echo "      .has-luminous-dusk-gradient-background {\n";
echo "        background: var(--wp--preset--gradient--luminous-dusk) !important;\n";
echo "      }\n";
echo "      .has-pale-ocean-gradient-background {\n";
echo "        background: var(--wp--preset--gradient--pale-ocean) !important;\n";
echo "      }\n";
echo "      .has-electric-grass-gradient-background {\n";
echo "        background: var(--wp--preset--gradient--electric-grass) !important;\n";
echo "      }\n";
echo "      .has-midnight-gradient-background {\n";
echo "        background: var(--wp--preset--gradient--midnight) !important;\n";
echo "      }\n";
echo "      .has-small-font-size {\n";
echo "        font-size: var(--wp--preset--font-size--small) !important;\n";
echo "      }\n";
echo "      .has-medium-font-size {\n";
echo "        font-size: var(--wp--preset--font-size--medium) !important;\n";
echo "      }\n";
echo "      .has-large-font-size {\n";
echo "        font-size: var(--wp--preset--font-size--large) !important;\n";
echo "      }\n";
echo "      .has-x-large-font-size {\n";
echo "        font-size: var(--wp--preset--font-size--x-large) !important;\n";
echo "      }\n";
echo "    </style>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/jquery.slicknav.min.js?ver=1.0.10\"\n";
echo "      id=\"slicknav-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/owl.carousel.min.js?ver=2.3.4\"\n";
echo "      id=\"owl-js\"\n";
echo "    ></script>\n";
echo "    <script\n";
echo "      type=\"text/javascript\"\n";
echo "      src=\"js/clipboard.min.js?ver=2.0.11\"\n";
echo "      id=\"clipboard-js\"\n";
echo "    ></script>\n";
echo "  </body>\n";
echo "</html>\n";
?>